### PR TITLE
Create sql_information_protection_default.json

### PR DESCRIPTION
**Pull request by DavidTrigano**

### CODE REVIEW

**Comment by DavidTrigano** [comment]
#sign-off

**Comment by DavidTrigano** [comment]
@mumian Not sure if you are the right contact. But could you please review this PR or add someone with enough permission to review and merge this PR?
Thanks,
D.

**Comment by DavidTrigano** [comment]
Adding @davidsmatlak as well for assistance

**Comment by mumian** [comment]
@DavidTrigano - This repo is used to store samples for the ARM documentation (https://docs.microsoft.com/en-us/azure/azure-resource-manager/). Can you share the reasons why you want to store this template in this repo? You might want to try Azure Quickstart templates (https://github.com/Azure/azure-quickstart-templates/tree/master/).

**Comment by DavidTrigano** [comment]
@mumian - I am actually trying to add a JSON file that will be showed in our public documentation of a product called Azure SQL Data Discovery & Classification. I am not looking to store an ARM template neither a QuickStart. Any idea where I could store it?

**Comment by mumian** [comment]
@DavidTrigano - Can you create your own GitHub repo?

**Comment by DavidTrigano** [comment]
@mumian Done. thank you for your assistance. I will go ahead and close this PR

**Pull request closed without merging**
