### PR TITLE
Adds Bicep examples for storage accounts

### PR DESCRIPTION
**Pull request by davidsmatlak**
- Adds three Bicep examples to create storage accounts.
- Updates Bicep symbolic names to camelCase and adds parameter for location.
- Updates schema, API version, parameters, and indentation for JSON files.

### CODE REVIEW

**Comment by tfitzmac** [comment]
@davidsmatlak - I think it might be better to use camel casing for the resource symbolic name. I thought that was the convention we were trying to use.

**Comment by davidsmatlak** [comment]
@tfitzmac Thanks for the feedback. I updated the files.

**Comment by tfitzmac** [comment]
@davidsmatlak - sorry, I noticed one more thing. Location for the storage resource should be set to a param that defaults to resourceGroup().location. That gives the convenience of not having to pass in the value but also letting people override the resource group location if they want to.

**Comment by davidsmatlak** [comment]
@tfitzmac Thanks for the feedback. I made the parameter change in the Bicep files and updated the JSON templates to include a location parameter.

**Pull request merged**
